name: Continuous Delivery

on:
  push:
    branches:
      - "master"

jobs:
  deploy:
    name: Deploy to fly.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions@master
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_TOKEN }}
        with:
          args: "deploy"
