name: Continuous Delivery

on:
  push:
    branches:
      - "master"

jobs:
  test:
    name: Mix Test
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v2
      - uses: nanasess/setup-chromedriver@master
      - name: Set up Erlang/OTP + Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: 1.12.x
          otp-version: 24.x
      - name: Recover deps cache
        uses: actions/cache@v2
        with:
          path: deps
          key: ${{ runner.OS }}-deps-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.OS }}-deps-${{ env.cache-name }}-
            ${{ runner.OS }}-deps-
      - name: Recover build cache
        uses: actions/cache@v2
        with:
          path: _build
          key: ${{ runner.OS }}-build-${{ github.ref }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ github.ref }}
            ${{ runner.OS }}-build-
      - run: mix setup
      - run: mix assets.deploy
      - run: mix test
      - name: Archive screenshots on failure
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: test-failure-screenshots
          path: screenshots

  deploy:
    name: Deploy to fly.io
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions@master
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_TOKEN }}
        with:
          args: "deploy"
